services:
  postgres:
    container_name: postgres
    image: postgres:15.3
    volumes:
      - postgres:/var/lib/postgres/data
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

#  backend:
#    container_name: backend
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command:
#      python3 src/main.py
#    ports:
#      - "8000:8000"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: